---
# -- Disable 1 level-1 header limit
# Linter complains when a 1 level-1 header is present
# while title is set in YAML metadata block.
MD025: false

# -- Extend line length to 100
MD013:
  line_length: 100

# -- Allow exclamation mark in titles
MD026:
  punctuation: ".,;:。，；："
