---
site_name: Wiki
repo_name: "loicreynier/wiki"
repo_url: "https://github.com/loicreynier/wiki"

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - pymdownx.keys

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - content.tabs.link

plugins:
  - tags
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Paris
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
