site_name: Wiki
repo_name: "loicreynier/wiki"
repo_url: "https://github.com/loicreynier/wiki"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - .NexusThemes/extra.css

theme:
  name: material
  palette:
    scheme: nexus-slate

  # Material for MkDocs default with light/dark toggle
  # palette:
  #   - media: "(prefers-color-scheme)"
  #     toggle:
  #       icon: material/link
  #       name: Switch to light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     toggle:
  #       icon: material/toggle-switch-off
  #       name: Switch to system preference

plugins:
  - tags
  - git-revision-date-localized:
      type: timeago
      timezone: Europe/Paris
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
